"""empty message

Revision ID: 0c643e47eb15
Revises: 549edf2d2669
Create Date: 2022-08-16 12:09:59.234452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c643e47eb15'
down_revision = '549edf2d2669'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('customer_contact_no', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'customer_contact_no')
    # ### end Alembic commands ###
