"""empty message

Revision ID: 3fd63ca69c19
Revises: b5c01273e886
Create Date: 2023-05-03 11:43:48.748136

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3fd63ca69c19'
down_revision = 'b5c01273e886'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('instamojo_payment_id', sa.String(length=255), nullable=True))
    op.add_column('receipts', sa.Column('instamojo_payment_request_id', sa.String(length=255), nullable=True))
    op.add_column('receipts', sa.Column('is_payment_completed', sa.Boolean(), nullable=True))
    op.drop_index('razorpay_order_id', table_name='receipts')
    op.drop_index('razorpay_payment_id', table_name='receipts')
    op.drop_index('razorpay_payment_signature', table_name='receipts')
    op.create_unique_constraint(None, 'receipts', ['instamojo_payment_id'])
    op.create_unique_constraint(None, 'receipts', ['instamojo_payment_request_id'])
    op.drop_column('receipts', 'razorpay_payment_id')
    op.drop_column('receipts', 'razorpay_order_id')
    op.drop_column('receipts', 'razorpay_payment_signature')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('razorpay_payment_signature', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('receipts', sa.Column('razorpay_order_id', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('receipts', sa.Column('razorpay_payment_id', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'receipts', type_='unique')
    op.drop_constraint(None, 'receipts', type_='unique')
    op.create_index('razorpay_payment_signature', 'receipts', ['razorpay_payment_signature'], unique=False)
    op.create_index('razorpay_payment_id', 'receipts', ['razorpay_payment_id'], unique=False)
    op.create_index('razorpay_order_id', 'receipts', ['razorpay_order_id'], unique=False)
    op.drop_column('receipts', 'is_payment_completed')
    op.drop_column('receipts', 'instamojo_payment_request_id')
    op.drop_column('receipts', 'instamojo_payment_id')
    # ### end Alembic commands ###
