"""empty message

Revision ID: 549edf2d2669
Revises: ad1fe4b09a47
Create Date: 2022-08-16 09:56:13.132158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '549edf2d2669'
down_revision = 'ad1fe4b09a47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('receipt_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipts', 'receipt_date')
    # ### end Alembic commands ###
