"""empty message

Revision ID: 6db180122676
Revises: aec9d51fcde6
Create Date: 2022-08-12 12:27:10.601615

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6db180122676'
down_revision = 'aec9d51fcde6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.String(length=255), nullable=True),
    sa.Column('receipt_total', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipts_receipt_id'), 'receipts', ['receipt_id'], unique=True)
    op.create_index(op.f('ix_receipts_receipt_total'), 'receipts', ['receipt_total'], unique=True)
    op.add_column('orders', sa.Column('receipt_id', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('order_admin_id', sa.String(length=255), nullable=True))
    op.drop_column('orders', 'order_product_image')
    op.drop_column('orders', 'order_product_name')
    op.drop_column('orders', 'order_product_price')
    op.drop_column('orders', 'order_vendor_id')
    op.drop_column('orders', 'order_product_discount')
    op.drop_column('orders', 'order_product_description')
    op.drop_column('orders', 'order_product_is_available')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_product_is_available', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('order_product_description', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('orders', sa.Column('order_product_discount', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('orders', sa.Column('order_vendor_id', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('orders', sa.Column('order_product_price', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('orders', sa.Column('order_product_name', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('orders', sa.Column('order_product_image', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('orders', 'order_admin_id')
    op.drop_column('orders', 'receipt_id')
    op.drop_index(op.f('ix_receipts_receipt_total'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_receipt_id'), table_name='receipts')
    op.drop_table('receipts')
    # ### end Alembic commands ###
