"""empty message

Revision ID: 9d7f23f78ec7
Revises: 6db180122676
Create Date: 2022-08-12 12:47:08.900552

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9d7f23f78ec7'
down_revision = '6db180122676'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_owner_id', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('order_total_amount', sa.String(length=255), nullable=True))
    op.drop_column('orders', 'order_admin_id')
    op.drop_column('orders', 'order_total_price')
    op.add_column('receipts', sa.Column('receipt_total_amount', sa.String(length=255), nullable=True))
    op.drop_index('ix_receipts_receipt_total', table_name='receipts')
    op.create_index(op.f('ix_receipts_receipt_total_amount'), 'receipts', ['receipt_total_amount'], unique=True)
    op.drop_column('receipts', 'receipt_total')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('receipt_total', mysql.VARCHAR(length=255), nullable=True))
    op.drop_index(op.f('ix_receipts_receipt_total_amount'), table_name='receipts')
    op.create_index('ix_receipts_receipt_total', 'receipts', ['receipt_total'], unique=False)
    op.drop_column('receipts', 'receipt_total_amount')
    op.add_column('orders', sa.Column('order_total_price', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('orders', sa.Column('order_admin_id', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('orders', 'order_total_amount')
    op.drop_column('orders', 'order_owner_id')
    # ### end Alembic commands ###
