"""empty message

Revision ID: a4539f098ed6
Revises: 10831e0f4f23
Create Date: 2022-08-26 11:41:32.922267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4539f098ed6'
down_revision = '10831e0f4f23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('wishlist_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'wishlist_data')
    # ### end Alembic commands ###
