"""empty message

Revision ID: ad1fe4b09a47
Revises: 726e970132a0
Create Date: 2022-08-16 09:33:56.766812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad1fe4b09a47'
down_revision = '726e970132a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_name', sa.String(length=255), nullable=True))
    op.add_column('receipts', sa.Column('customer_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipts', 'customer_id')
    op.drop_column('orders', 'order_name')
    # ### end Alembic commands ###
