"""empty message

Revision ID: aec9d51fcde6
Revises: fd391382bd62
Create Date: 2022-07-22 11:34:14.540699

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aec9d51fcde6'
down_revision = 'fd391382bd62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_address', sa.String(length=255), nullable=True))
    op.drop_column('orders', 'oder_address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('oder_address', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('orders', 'order_address')
    # ### end Alembic commands ###
