"""empty message

Revision ID: b5c01273e886
Revises: ec7e075ddf10
Create Date: 2022-09-16 10:05:49.314467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5c01273e886'
down_revision = 'ec7e075ddf10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('razorpay_order_id', sa.String(length=255), nullable=True))
    op.add_column('receipts', sa.Column('razorpay_payment_id', sa.String(length=255), nullable=True))
    op.add_column('receipts', sa.Column('razorpay_payment_signature', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'receipts', ['razorpay_order_id'])
    op.create_unique_constraint(None, 'receipts', ['razorpay_payment_id'])
    op.create_unique_constraint(None, 'receipts', ['razorpay_payment_signature'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'receipts', type_='unique')
    op.drop_constraint(None, 'receipts', type_='unique')
    op.drop_constraint(None, 'receipts', type_='unique')
    op.drop_column('receipts', 'razorpay_payment_signature')
    op.drop_column('receipts', 'razorpay_payment_id')
    op.drop_column('receipts', 'razorpay_order_id')
    # ### end Alembic commands ###
