"""empty message

Revision ID: cab47d7dbf7d
Revises: 0c643e47eb15
Create Date: 2022-08-17 10:30:20.085831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cab47d7dbf7d'
down_revision = '0c643e47eb15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_status', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('order_tracking_id', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('order_delivery_partner', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'order_delivery_partner')
    op.drop_column('orders', 'order_tracking_id')
    op.drop_column('orders', 'order_status')
    # ### end Alembic commands ###
