"""empty message

Revision ID: ec7e075ddf10
Revises: 68ee8ffa2a5a
Create Date: 2022-08-30 11:29:03.220941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec7e075ddf10'
down_revision = '68ee8ffa2a5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'date')
    # ### end Alembic commands ###
