"""empty message

Revision ID: fd391382bd62
Revises: 04ef856d9eac
Create Date: 2022-07-21 11:27:08.685442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd391382bd62'
down_revision = '04ef856d9eac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('oder_address', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('order_contact_no', sa.String(length=255), nullable=True))
    op.drop_index('ix_orders_order_id', table_name='orders')
    op.create_index(op.f('ix_orders_order_id'), 'orders', ['order_id'], unique=True)
    op.add_column('products', sa.Column('product_category', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('product_is_new', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('product_is_best_seller', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'product_is_best_seller')
    op.drop_column('products', 'product_is_new')
    op.drop_column('products', 'product_category')
    op.drop_index(op.f('ix_orders_order_id'), table_name='orders')
    op.create_index('ix_orders_order_id', 'orders', ['order_id'], unique=False)
    op.drop_column('orders', 'order_contact_no')
    op.drop_column('orders', 'oder_address')
    # ### end Alembic commands ###
